name: Linting
on: [pull_request, workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - uses: astral-sh/ruff-action@v3

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest tests


