name: Linting and Testing
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install project
        run: uv sync --locked --all-extras --dev
      - name: Run tests
        run: uv run pytest pyhgvs/tests
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
      - name: Test import 
        run: uv run --with <PACKAGE> --no-project -- python -c "import <PACKAGE>"